[2023-02-05 06:35:02,544] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: Train.Server scheduled__2023-02-03T15:00:00+00:00 [queued]>
[2023-02-05 06:35:02,549] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: Train.Server scheduled__2023-02-03T15:00:00+00:00 [queued]>
[2023-02-05 06:35:02,549] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-02-05 06:35:02,549] {taskinstance.py:1242} INFO - Starting attempt 2 of 1
[2023-02-05 06:35:02,549] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-02-05 06:35:02,560] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): Server> on 2023-02-03 15:00:00+00:00
[2023-02-05 06:35:02,562] {standard_task_runner.py:52} INFO - Started process 86023 to run task
[2023-02-05 06:35:02,565] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Train', 'Server', 'scheduled__2023-02-03T15:00:00+00:00', '--job-id', '58', '--raw', '--subdir', '/opt/ml/git/final-project-level3-recsys-02/Airflow/dags/RecSys_02.py', '--cfg-path', '/tmp/tmp23riz53m', '--error-file', '/tmp/tmp6_9hyzu7']
[2023-02-05 06:35:02,565] {standard_task_runner.py:77} INFO - Job 58: Subtask Server
[2023-02-05 06:35:02,587] {logging_mixin.py:109} INFO - Running <TaskInstance: Train.Server scheduled__2023-02-03T15:00:00+00:00 [running]> on host 3ab801c1e2ef
[2023-02-05 06:35:02,610] {taskinstance.py:1412} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=RecSys-02
AIRFLOW_CTX_DAG_ID=Train
AIRFLOW_CTX_TASK_ID=Server
AIRFLOW_CTX_EXECUTION_DATE=2023-02-03T15:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-03T15:00:00+00:00
[2023-02-05 06:35:02,611] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-02-05 06:35:02,611] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'bentoml serve --port 30001 MyService:latest']
[2023-02-05 06:35:02,617] {subprocess.py:85} INFO - Output:
[2023-02-05 06:35:03,630] {subprocess.py:89} INFO - [2023-02-05 06:35:03,630] INFO - Getting latest version MyService:20230204194211_A3AA9B
[2023-02-05 06:35:03,639] {subprocess.py:89} INFO - [2023-02-05 06:35:03,639] INFO - Starting BentoML API proxy in development mode..
[2023-02-05 06:35:03,640] {subprocess.py:89} INFO - [2023-02-05 06:35:03,640] INFO - Starting BentoML API server in development mode..
[2023-02-05 06:35:03,765] {subprocess.py:89} INFO - [2023-02-05 06:35:03,764] INFO - Your system nofile limit is 1048576, which means each instance of microbatch service is able to hold this number of connections at same time. You can increase the number of file descriptors for the server process, or launch more microbatch instances to accept more concurrent connection.
[2023-02-05 06:35:07,598] {local_task_job.py:211} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-02-05 06:35:07,599] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 86023
[2023-02-05 06:35:07,599] {taskinstance.py:1396} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-02-05 06:35:07,599] {subprocess.py:99} INFO - Sending SIGTERM signal to process group
[2023-02-05 06:35:07,600] {taskinstance.py:1686} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/ml/.cache/pypoetry/virtualenvs/01-bentoml-kzmRLtjI-py3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/opt/ml/.cache/pypoetry/virtualenvs/01-bentoml-kzmRLtjI-py3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/opt/ml/.cache/pypoetry/virtualenvs/01-bentoml-kzmRLtjI-py3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1499, in _execute_task
    result = execute_callable(context=context)
  File "/opt/ml/.cache/pypoetry/virtualenvs/01-bentoml-kzmRLtjI-py3.8/lib/python3.8/site-packages/airflow/operators/bash.py", line 178, in execute
    result = self.subprocess_hook.run_command(
  File "/opt/ml/.cache/pypoetry/virtualenvs/01-bentoml-kzmRLtjI-py3.8/lib/python3.8/site-packages/airflow/hooks/subprocess.py", line 87, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b''):
  File "/opt/ml/.cache/pypoetry/virtualenvs/01-bentoml-kzmRLtjI-py3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1398, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-02-05 06:35:07,607] {taskinstance.py:1270} INFO - Marking task as FAILED. dag_id=Train, task_id=Server, execution_date=20230203T150000, start_date=20230205T063502, end_date=20230205T063507
[2023-02-05 06:35:07,623] {standard_task_runner.py:88} ERROR - Failed to execute job 58 for task Server
Traceback (most recent call last):
  File "/opt/ml/.cache/pypoetry/virtualenvs/01-bentoml-kzmRLtjI-py3.8/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/opt/ml/.cache/pypoetry/virtualenvs/01-bentoml-kzmRLtjI-py3.8/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/opt/ml/.cache/pypoetry/virtualenvs/01-bentoml-kzmRLtjI-py3.8/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/opt/ml/.cache/pypoetry/virtualenvs/01-bentoml-kzmRLtjI-py3.8/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/opt/ml/.cache/pypoetry/virtualenvs/01-bentoml-kzmRLtjI-py3.8/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/opt/ml/.cache/pypoetry/virtualenvs/01-bentoml-kzmRLtjI-py3.8/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/opt/ml/.cache/pypoetry/virtualenvs/01-bentoml-kzmRLtjI-py3.8/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/opt/ml/.cache/pypoetry/virtualenvs/01-bentoml-kzmRLtjI-py3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/opt/ml/.cache/pypoetry/virtualenvs/01-bentoml-kzmRLtjI-py3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/opt/ml/.cache/pypoetry/virtualenvs/01-bentoml-kzmRLtjI-py3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1499, in _execute_task
    result = execute_callable(context=context)
  File "/opt/ml/.cache/pypoetry/virtualenvs/01-bentoml-kzmRLtjI-py3.8/lib/python3.8/site-packages/airflow/operators/bash.py", line 178, in execute
    result = self.subprocess_hook.run_command(
  File "/opt/ml/.cache/pypoetry/virtualenvs/01-bentoml-kzmRLtjI-py3.8/lib/python3.8/site-packages/airflow/hooks/subprocess.py", line 87, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b''):
  File "/opt/ml/.cache/pypoetry/virtualenvs/01-bentoml-kzmRLtjI-py3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1398, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-02-05 06:35:07,941] {process_utils.py:66} INFO - Process psutil.Process(pid=86023, status='terminated', exitcode=1, started='06:35:02') (86023) terminated with exit code 1
[2023-02-05 06:35:08,314] {process_utils.py:66} INFO - Process psutil.Process(pid=86033, status='terminated', started='06:35:03') (86033) terminated with exit code None
[2023-02-05 06:35:08,321] {process_utils.py:66} INFO - Process psutil.Process(pid=86024, status='terminated', started='06:35:02') (86024) terminated with exit code None
