[2023-02-04 19:23:29,326] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: Train.Termination scheduled__2023-02-02T15:00:00+00:00 [queued]>
[2023-02-04 19:23:29,333] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: Train.Termination scheduled__2023-02-02T15:00:00+00:00 [queued]>
[2023-02-04 19:23:29,333] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-02-04 19:23:29,333] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-02-04 19:23:29,333] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-02-04 19:23:29,343] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): Termination> on 2023-02-02 15:00:00+00:00
[2023-02-04 19:23:29,345] {standard_task_runner.py:52} INFO - Started process 84585 to run task
[2023-02-04 19:23:29,348] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Train', 'Termination', 'scheduled__2023-02-02T15:00:00+00:00', '--job-id', '49', '--raw', '--subdir', '/opt/ml/git/final-project-level3-recsys-02/Airflow/dags/RecSys_02.py', '--cfg-path', '/tmp/tmp_jz_ji4_', '--error-file', '/tmp/tmpk2opircv']
[2023-02-04 19:23:29,349] {standard_task_runner.py:77} INFO - Job 49: Subtask Termination
[2023-02-04 19:23:29,371] {logging_mixin.py:109} INFO - Running <TaskInstance: Train.Termination scheduled__2023-02-02T15:00:00+00:00 [running]> on host 3ab801c1e2ef
[2023-02-04 19:23:29,394] {taskinstance.py:1412} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=RecSys-02
AIRFLOW_CTX_DAG_ID=Train
AIRFLOW_CTX_TASK_ID=Termination
AIRFLOW_CTX_EXECUTION_DATE=2023-02-02T15:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-02T15:00:00+00:00
[2023-02-04 19:23:29,395] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-02-04 19:23:29,396] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'pkill -9 bentoml']
[2023-02-04 19:23:29,401] {subprocess.py:85} INFO - Output:
[2023-02-04 19:23:29,405] {subprocess.py:93} INFO - Command exited with return code 1
[2023-02-04 19:23:29,405] {taskinstance.py:1686} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/ml/.cache/pypoetry/virtualenvs/01-bentoml-kzmRLtjI-py3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/opt/ml/.cache/pypoetry/virtualenvs/01-bentoml-kzmRLtjI-py3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/opt/ml/.cache/pypoetry/virtualenvs/01-bentoml-kzmRLtjI-py3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1499, in _execute_task
    result = execute_callable(context=context)
  File "/opt/ml/.cache/pypoetry/virtualenvs/01-bentoml-kzmRLtjI-py3.8/lib/python3.8/site-packages/airflow/operators/bash.py", line 187, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-02-04 19:23:29,412] {taskinstance.py:1270} INFO - Marking task as FAILED. dag_id=Train, task_id=Termination, execution_date=20230202T150000, start_date=20230204T192329, end_date=20230204T192329
[2023-02-04 19:23:29,421] {standard_task_runner.py:88} ERROR - Failed to execute job 49 for task Termination
Traceback (most recent call last):
  File "/opt/ml/.cache/pypoetry/virtualenvs/01-bentoml-kzmRLtjI-py3.8/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/opt/ml/.cache/pypoetry/virtualenvs/01-bentoml-kzmRLtjI-py3.8/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/opt/ml/.cache/pypoetry/virtualenvs/01-bentoml-kzmRLtjI-py3.8/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/opt/ml/.cache/pypoetry/virtualenvs/01-bentoml-kzmRLtjI-py3.8/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/opt/ml/.cache/pypoetry/virtualenvs/01-bentoml-kzmRLtjI-py3.8/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/opt/ml/.cache/pypoetry/virtualenvs/01-bentoml-kzmRLtjI-py3.8/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/opt/ml/.cache/pypoetry/virtualenvs/01-bentoml-kzmRLtjI-py3.8/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/opt/ml/.cache/pypoetry/virtualenvs/01-bentoml-kzmRLtjI-py3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/opt/ml/.cache/pypoetry/virtualenvs/01-bentoml-kzmRLtjI-py3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/opt/ml/.cache/pypoetry/virtualenvs/01-bentoml-kzmRLtjI-py3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1499, in _execute_task
    result = execute_callable(context=context)
  File "/opt/ml/.cache/pypoetry/virtualenvs/01-bentoml-kzmRLtjI-py3.8/lib/python3.8/site-packages/airflow/operators/bash.py", line 187, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-02-04 19:23:29,439] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-02-04 19:23:29,459] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
